Add new sample with the implementation of the batch operations in node js
southworks/Microsoft-Teams-Samples pull request #5
Opened 2023-09-04 19:37 UTC by JhontSouth

## Description
This PR adds the new sample _**bot-batch-operations**_ that includes the uses of the Teams batch APIs in node js.

## Specific Changes
- Created the _**bot-batch-operations**_ sample in nodejs.
- Added the logic to use the new features in _**TeamsBatchOperationsBot.**_
- Added the README guide to use the new bot.

## Testing
The following images show some sample bot responses.
![GetFailedEntries](https://github.com/southworks/Microsoft-Teams-Samples/assets/122501764/6cd0469f-2a22-4b3c-a579-cec3d26f00cc)
![MessageAListOfUsers](https://github.com/southworks/Microsoft-Teams-Samples/assets/122501764/a78e7938-18aa-44ec-992a-496518825ea4)

2023-09-05 11:47 UTC, ceciliaavila requested changes

2023-09-05 11:47 UTC, ceciliaavila commented on samples/bot-batch-operations/nodejs/assets/sample.json
> +[
This file should be updated with the sample name and capacities.

2023-09-05 11:47 UTC, ceciliaavila commented on samples/bot-batch-operations/nodejs/bots/teamsConversationBot.js
> +class TeamsConversationBot extends TeamsActivityHandler {
This should be called TeamsBatchOperationsBot

2023-09-05 11:47 UTC, ceciliaavila commented on samples/bot-batch-operations/nodejs/bots/teamsConversationBot.js
> +    }
This method is not used in this bot. Please remove unused functionality.

2023-09-05 11:47 UTC, ceciliaavila commented on samples/bot-batch-operations/nodejs/index.js
> +// Import required pckages
```suggestion
// Import required packages
```

2023-09-05 11:47 UTC, ceciliaavila commented on samples/bot-batch-operations/nodejs/index.js
> +const { TeamsConversationBot } = require('./bots/teamsConversationBot');
The class name and the file name should be changed.

2023-09-05 17:42 UTC, ceciliaavila requested changes

2023-09-05 17:42 UTC, ceciliaavila commented on samples/bot-batch-operations/nodejs/assets/sample.json
> +        "url": "https://raw.githubusercontent.com/southworks/Microsoft-Teams-Samples/bf92bc9c53ed366037c70c51af8432782575cecf/samples/bot-batch-operations/nodejs/Images/GetFailedEntries.png",
Don't use the SW fork. Leave the main branch URL even when the sample does not exist yet.

2023-09-05 17:42 UTC, ceciliaavila commented on samples/bot-batch-operations/nodejs/assets/sample.json
> +        "alt": "Image showing one of the Batch Operations (Get Failed Entres) available from Bot Framework v4"
Be careful with the typos.
```suggestion
        "alt": "Image showing one of the Batch Operations (Get Failed Entries) available from Bot Framework v4"
```

2023-09-05 19:08 UTC, ceciliaavila approved these changes

2023-09-06 13:19 UTC, sw-joelmut approved these changes

2023-09-08 16:49 UTC, ceciliaavila commented
/promoted 955

2023-09-08 16:49 UTC, closed without merging